# Generated by Django 5.2.3 on 2025-08-13 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
        ('form_app', '0002_hello'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_app.form')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
