# Generated by Django 5.2.3 on 2025-08-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0003_formpluginmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='action',
            field=models.CharField(blank=True, help_text='URL para onde o formulário será enviado. Deixe em branco para usar a URL atual.', max_length=255),
        ),
    ]
