# Generated by Django 5.2.3 on 2025-08-13 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
        ('form_app', '0004_form_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormFieldPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('field_type', models.CharField(choices=[('text', 'Texto'), ('email', 'Email'), ('number', 'Número'), ('textarea', 'Área de Texto'), ('select', 'Seleção')], default='text', max_length=50)),
                ('label', models.CharField(help_text='Rótulo do campo', max_length=100)),
                ('required', models.BooleanField(default=True, help_text='Campo obrigatório?')),
            ],
            options={
                'verbose_name': 'Campo do Formulário',
                'verbose_name_plural': 'Campos do Formulário',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
