# Generated by Django 5.2.3 on 2025-08-13 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0005_formfieldplugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfieldplugin',
            name='name',
            field=models.CharField(blank=True, help_text='Nome do campo (usado no HTML)', max_length=100, unique=True),
        ),
    ]
