# Generated by Django 5.2.3 on 2025-08-13 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0006_formfieldplugin_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_app.form')),
            ],
            options={
                'verbose_name': 'Submissão de Formulário',
                'verbose_name_plural': 'Submissões de Formulário',
            },
        ),
    ]
