# Generated by Django 5.2.3 on 2025-08-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0007_formsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfieldplugin',
            name='name',
            field=models.CharField(blank=True, help_text='Nome do campo (usado no HTML)', max_length=100),
        ),
    ]

