# Generated by Django 5.2.3 on 2025-08-15 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
        ('form_app', '0008_alter_formfieldplugin_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormFieldIBGEPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('label', models.CharField(default='Campo IBGE', help_text='Rótulo do campo', max_length=100)),
                ('name', models.CharField(blank=True, help_text='Nome do campo (Usado no HTML)', max_length=100)),
                ('required', models.BooleanField(default=True, help_text='Campo obrigatório?')),
            ],
            options={
                'verbose_name': 'Campo da API',
                'verbose_name_plural': 'Campos da API',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.RenameModel(
            old_name='FormFieldPlugin',
            new_name='FormFieldPluginModel',
        ),
        migrations.CreateModel(
            name='FormFieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='form_app.formfieldpluginmodel')),
            ],
            options={
                'verbose_name': 'Opção de select',
                'verbose_name_plural': 'Opções de select',
            },
        ),
    ]
